#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import json
import os
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlencode
from urllib.request import Request, urlopen


DEFAULT_BATCH_SIZE = 100
DEFAULT_PIPELINE_STAGES = [
    {"name": "New", "order": 0, "color": "#3b82f6", "system_key": "new"},
    {"name": "Contacted", "order": 1, "color": "#f59e0b", "system_key": "contacted"},
    {"name": "Interested", "order": 2, "color": "#10b981", "system_key": "interested"},
    {"name": "Call booked", "order": 3, "color": "#7c3aed", "system_key": "call_booked"},
    {"name": "Closed", "order": 4, "color": "#059669", "system_key": "closed"},
]


class SupabaseImportError(Exception):
    pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import a normalized contacts CSV into Supabase for the SPEAQI CRM."
    )
    parser.add_argument("input_csv", help="Path to contacts_import.csv generated by the analyzer.")
    parser.add_argument("--email", help="CRM login email for user-scoped import.")
    parser.add_argument("--password", help="CRM login password for user-scoped import.")
    parser.add_argument("--access-token", help="Existing Supabase access token as an alternative to email/password.")
    parser.add_argument("--user-id", help="Explicit target user ID. Required with service-role auth.")
    parser.add_argument(
        "--supabase-url",
        help="Supabase project URL. Defaults to NEXT_PUBLIC_SUPABASE_URL from .env.local.",
    )
    parser.add_argument(
        "--anon-key",
        help="Supabase anon key. Defaults to NEXT_PUBLIC_SUPABASE_ANON_KEY from .env.local.",
    )
    parser.add_argument(
        "--service-role-key",
        help="Supabase service role key. Defaults to SUPABASE_SERVICE_ROLE_KEY from .env.local.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=f"Number of rows per insert batch (default: {DEFAULT_BATCH_SIZE}).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate the CSV and print what would be imported without touching Supabase.",
    )
    parser.add_argument(
        "--contact-scope",
        choices=["crm", "holding"],
        default="crm",
        help="Store imported rows directly in CRM or in a separate holding list (default: crm).",
    )
    return parser.parse_args()


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip("'").strip('"'))


def chunked(items: list[Any], size: int) -> list[list[Any]]:
    return [items[index : index + size] for index in range(0, len(items), size)]


def normalize_text(value: str | None) -> str | None:
    cleaned = (value or "").strip()
    return cleaned or None


def normalize_priority(value: str | None) -> int:
    try:
        return max(0, min(3, int(float((value or "0").strip() or "0"))))
    except ValueError:
        return 0


def normalize_numeric(value: str | None) -> float | None:
    cleaned = (value or "").strip()
    if not cleaned:
        return None
    try:
        return float(cleaned)
    except ValueError:
        return None


def read_contacts_csv(path: Path) -> list[dict[str, Any]]:
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        headers = set(reader.fieldnames or [])
        required = {"legacy_id", "name", "status", "source", "priority", "next_followup_at"}
        missing = sorted(required - headers)
        if missing:
            raise SupabaseImportError(f"Missing required CSV columns: {', '.join(missing)}")

        records = []
        for row in reader:
            records.append(
                {
                    "legacy_id": normalize_text(row.get("legacy_id")),
                    "name": normalize_text(row.get("name")) or "Lead legacy",
                    "email": normalize_text(row.get("email")),
                    "phone": normalize_text(row.get("phone")),
                    "status": normalize_text(row.get("status")) or "New",
                    "source": normalize_text(row.get("source")) or "legacy-kanban",
                    "contact_scope": "crm",
                    "priority": normalize_priority(row.get("priority")),
                    "responsible": normalize_text(row.get("responsible")),
                    "value": normalize_numeric(row.get("value")),
                    "note": normalize_text(row.get("note")),
                    "last_activity_summary": normalize_text(row.get("note")),
                    "next_followup_at": normalize_text(row.get("next_followup_at")),
                }
            )
    return records


def json_request(
    method: str,
    url: str,
    *,
    headers: dict[str, str] | None = None,
    data: Any = None,
) -> Any:
    body = None
    request_headers = {"Accept": "application/json"}
    if headers:
        request_headers.update(headers)
    if data is not None:
        body = json.dumps(data).encode("utf-8")
        request_headers.setdefault("Content-Type", "application/json")

    request = Request(url, data=body, headers=request_headers, method=method)
    try:
        with urlopen(request) as response:
            payload = response.read().decode("utf-8")
            if not payload:
                return None
            return json.loads(payload)
    except HTTPError as error:
        details = error.read().decode("utf-8", errors="replace")
        raise SupabaseImportError(f"{method} {url} failed: {error.code} {details}") from error
    except URLError as error:
        raise SupabaseImportError(f"{method} {url} failed: {error.reason}") from error


def auth_headers(api_key: str, access_token: str | None = None, *, extra: dict[str, str] | None = None) -> dict[str, str]:
    headers = {
        "apikey": api_key,
        "Authorization": f"Bearer {access_token or api_key}",
    }
    if extra:
        headers.update(extra)
    return headers


def sign_in_with_password(base_url: str, anon_key: str, email: str, password: str) -> tuple[str, str]:
    auth_url = f"{base_url}/auth/v1/token?grant_type=password"
    payload = {"email": email, "password": password}
    response = json_request("POST", auth_url, headers={"apikey": anon_key}, data=payload)
    access_token = response.get("access_token")
    user = response.get("user") or {}
    user_id = user.get("id")
    if not access_token or not user_id:
        raise SupabaseImportError("Supabase sign-in did not return access_token and user.id")
    return access_token, user_id


def fetch_user_from_token(base_url: str, anon_key: str, access_token: str) -> str:
    response = json_request(
        "GET",
        f"{base_url}/auth/v1/user",
        headers=auth_headers(anon_key, access_token),
    )
    user_id = (response or {}).get("id")
    if not user_id:
        raise SupabaseImportError("Could not resolve user from access token")
    return user_id


def ensure_pipeline_stages(base_url: str, headers: dict[str, str], user_id: str, dry_run: bool) -> int:
    query = urlencode({"select": "id", "user_id": f"eq.{user_id}", "limit": "1"})
    existing = json_request("GET", f"{base_url}/rest/v1/pipeline_stages?{query}", headers=headers)
    if existing:
        return 0
    if dry_run:
        return len(DEFAULT_PIPELINE_STAGES)

    payload = [{**stage, "user_id": user_id} for stage in DEFAULT_PIPELINE_STAGES]
    inserted = json_request(
        "POST",
        f"{base_url}/rest/v1/pipeline_stages",
        headers={**headers, "Prefer": "return=representation"},
        data=payload,
    )
    return len(inserted or [])


def upsert_contacts(
    base_url: str,
    headers: dict[str, str],
    user_id: str,
    records: list[dict[str, Any]],
    batch_size: int,
    dry_run: bool,
    contact_scope: str,
) -> list[dict[str, Any]]:
    prepared = [
        {
            **record,
            "user_id": user_id,
            "contact_scope": contact_scope,
            "next_followup_at": None if contact_scope == "holding" else record.get("next_followup_at"),
            "next_action_at": None if contact_scope == "holding" else record.get("next_followup_at"),
            "last_activity_summary": (
                record.get("last_activity_summary")
                or ("Import CSV separato" if contact_scope == "holding" else "Import CSV")
            ),
        }
        for record in records
    ]
    if dry_run:
        return prepared

    inserted: list[dict[str, Any]] = []
    for batch in chunked(prepared, batch_size):
        response = json_request(
            "POST",
            f"{base_url}/rest/v1/contacts?on_conflict=user_id,legacy_id",
            headers={
                **headers,
                "Prefer": "resolution=merge-duplicates,return=representation",
            },
            data=batch,
        )
        inserted.extend(response or [])
    return inserted


def fetch_existing_followup_tasks(
    base_url: str,
    headers: dict[str, str],
    user_id: str,
    contact_ids: list[str],
) -> set[str]:
    existing: set[str] = set()
    for batch in chunked(contact_ids, 80):
        joined = ",".join(batch)
        query = (
            "select=contact_id"
            f"&user_id=eq.{quote(user_id, safe='')}"
            "&type=eq.follow-up"
            "&status=eq.pending"
            f"&contact_id=in.({quote(joined, safe=',-')})"
        )
        rows = json_request("GET", f"{base_url}/rest/v1/tasks?{query}", headers=headers) or []
        existing.update(row.get("contact_id") for row in rows if row.get("contact_id"))
    return existing


def insert_followup_tasks(
    base_url: str,
    headers: dict[str, str],
    user_id: str,
    contacts: list[dict[str, Any]],
    batch_size: int,
    dry_run: bool,
) -> int:
    contacts = [contact for contact in contacts if contact.get("contact_scope") != "holding"]
    open_contacts = [contact for contact in contacts if contact.get("status") != "Closed" and contact.get("next_followup_at")]
    if not open_contacts:
        return 0

    if dry_run:
        return len(open_contacts)

    open_contacts = [contact for contact in open_contacts if contact.get("id")]
    if not open_contacts:
        return 0

    existing_task_contacts = fetch_existing_followup_tasks(
        base_url,
        headers,
        user_id,
        [contact["id"] for contact in open_contacts],
    )
    payload = [
        {
            "user_id": user_id,
            "contact_id": contact["id"],
            "type": "follow-up",
            "due_date": contact["next_followup_at"],
            "status": "pending",
            "note": f"Follow-up importato da CSV per {contact['name']}",
        }
        for contact in open_contacts
        if contact["id"] not in existing_task_contacts
    ]
    if not payload:
        return 0

    created = 0
    for batch in chunked(payload, batch_size):
        response = json_request(
            "POST",
            f"{base_url}/rest/v1/tasks",
            headers={**headers, "Prefer": "return=representation"},
            data=batch,
        )
        created += len(response or [])
    return created


def resolve_auth(args: argparse.Namespace, base_url: str, anon_key: str, service_role_key: str | None) -> tuple[dict[str, str], str, str]:
    if args.dry_run and not any([service_role_key and args.user_id, args.access_token, args.email and args.password]):
        return {}, args.user_id or "dry-run", "dry_run"

    if service_role_key and args.user_id:
        return auth_headers(service_role_key), args.user_id, "service_role"

    if args.access_token:
        user_id = args.user_id or fetch_user_from_token(base_url, anon_key, args.access_token)
        return auth_headers(anon_key, args.access_token), user_id, "access_token"

    if args.email and args.password:
        access_token, user_id = sign_in_with_password(base_url, anon_key, args.email, args.password)
        return auth_headers(anon_key, access_token), user_id, "password"

    raise SupabaseImportError(
        "Provide either --email with --password, --access-token, or --user-id with a service role key."
    )


def main() -> int:
    load_env_file(Path(".env.local"))
    args = parse_args()
    input_csv = Path(args.input_csv).expanduser().resolve()
    if not input_csv.exists():
        raise SystemExit(f"Input CSV not found: {input_csv}")

    base_url = (args.supabase_url or os.environ.get("NEXT_PUBLIC_SUPABASE_URL") or "").rstrip("/")
    anon_key = args.anon_key or os.environ.get("NEXT_PUBLIC_SUPABASE_ANON_KEY")
    service_role_key = args.service_role_key or os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if not base_url or not anon_key:
        raise SystemExit("Supabase URL and anon key are required. Check .env.local or pass flags.")

    records = read_contacts_csv(input_csv)
    headers, user_id, auth_mode = resolve_auth(args, base_url, anon_key, service_role_key)

    existing_open = sum(1 for record in records if record["status"] != "Closed" and record["next_followup_at"])
    print(f"Input CSV: {input_csv}")
    print(f"Rows ready: {len(records)}")
    print(f"Open contacts with follow-up: {existing_open}")
    print(f"Contact scope: {args.contact_scope}")
    print(f"Auth mode: {auth_mode}")
    print(f"Target user: {user_id}")

    if auth_mode == "dry_run":
        stages_created = len(DEFAULT_PIPELINE_STAGES)
        contacts = upsert_contacts(base_url, headers, user_id, records, args.batch_size, True, args.contact_scope)
        tasks_created = insert_followup_tasks(base_url, headers, user_id, contacts, args.batch_size, True)
    else:
        stages_created = ensure_pipeline_stages(base_url, headers, user_id, args.dry_run)
        contacts = upsert_contacts(base_url, headers, user_id, records, args.batch_size, args.dry_run, args.contact_scope)
        tasks_created = insert_followup_tasks(base_url, headers, user_id, contacts, args.batch_size, args.dry_run)

    print(f"Pipeline stages created: {stages_created}")
    print(f"Contacts upserted: {len(contacts)}")
    print(f"Follow-up tasks created: {tasks_created}")
    print("Dry run only." if args.dry_run else "Import complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
